/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BpmnEditor: typeof import('./components/BpmnEditor.vue')['default']
    Designer: typeof import('./components/designer/Designer.vue')['default']
    ImageUploader: typeof import('./components/ImageUploader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./components/SearchForm.vue')['default']
    SvgIcon: typeof import('./components/svg-icon/SvgIcon.vue')['default']
  }
}
